ANDROID_OAUTH2_SECRET: qt1IQpGJ3gYSTT5ef7skTIXx
ASPECTS_CLICKHOUSE_CMS_PASSWORD: eV2hBFKpIDELnS8MyR5tZXYq
ASPECTS_CLICKHOUSE_CMS_USER: ch_cms
ASPECTS_CLICKHOUSE_LRS_PASSWORD: bglpa4DYZld1JP9Z7KG8ECEx
ASPECTS_CLICKHOUSE_LRS_USER: ch_lrs
ASPECTS_CLICKHOUSE_REPORT_PASSWORD: cAHJ4s86reuDcGyJZFDFhDfo
ASPECTS_CLICKHOUSE_REPORT_USER: ch_report
ASPECTS_CLICKHOUSE_VECTOR_PASSWORD: 970MR71jxSl8QW3AG6ZVvQEi
ASPECTS_CLICKHOUSE_VECTOR_USER: ch_vector
ASPECTS_ENABLE_PII: true
CADDY_HTTP_PORT: 81
CAIRN_CLICKHOUSE_PASSWORD: RuJaz9FKcl7L1cVKLrbO
CAIRN_POSTGRESQL_PASSWORD: bWRJwBAzUCC9ZVG0sBj5
CAIRN_SSO_CLIENT_SECRET: 1jnuX0h4B2gIrvoRbKhZ
CAIRN_SUPERSET_SECRET_KEY: yGw7uHdfkr6DIZf7vRwR
CLICKHOUSE_ADMIN_PASSWORD: eTeWgT2XTyovdzXypW10fyjA
CLICKHOUSE_ADMIN_USER: ch_admin
CLICKHOUSE_SECURE_CONNECTION: false
CMS_HOST: studio.trainficient.com
CMS_LANGUAGE: vi
CMS_OAUTH2_SECRET: RxseouCfhNG4UKT0VjgOaLjb
CONTACT_EMAIL: trainficient.official@gmail.com
ENABLE_HTTPS: true
ENABLE_WEB_PROXY: false
ID: yDCaNEPy4yrK2VihATZiGo8E
INDIGO_ENABLE_DARK_TOGGLE: false
INDIGO_PRIMARY_COLOR: '#3BECB9'
JWT_RSA_PRIVATE_KEY: |-
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAnUqyFzgJ7nv3JMMC5jrqbqy7e15c+UmvM+GEzfzlWtymnon4
  SLD8wI/tlQz5RirSPhDO6+heuR99VnZgHgAfdTuq3DOX1lsHnoK7LEo4yvGQl2jy
  iPyiVJ9DB3RfCwmrm2FPnW95kJYS8rWA7f6rKsHbV/5F9iIcsLQsJxh9ZTeAB6m+
  V5ilSx2QDvzVIDvv+qM9HiL31gflYDe4Gu8ugk3H16suKvtEOmK/l9GwF+/hLMRM
  +BW58TJqmrh7+cJL11EaH56mjdaMiPYxVALvx/eUvLeDXVC1+RoMcLf1pXKk5jYs
  tcGjHtEOibY8DlmHBUOtVnrlViQMI+4eTGmVHwIDAQABAoIBAAkjyCxu464uwuIp
  I20oZZXvxeckc7ztP1fW62YizgWqcP4hC0MsvEseMefUJ1SgnrM05n6Gc/adh1Ae
  XyBvJmTOsPN3BgQn1E4Cz7Ms+ZbaqZRlaJkgK6NE1oVuNCr1MWUSfFNWy8Fkjw5O
  ZgMDpi49ByyvnaDF7lUwQFPh6ZYXfO5r5cW6FLdT59PWSM4KguqzJ8AsVlCKBlLU
  MAvtlt/AwB6HiXzVYLawVeeZewDu70rXsWkLya/+DAHl+2kNWTbt7PpRbiMoY1j5
  HrDxxpDvEN9eos4xa9IZ4ajAFIgKpgqMkMhw7q2o9Aij4m67lgNGmrCUu3nAVoW1
  aCjQhr0CgYEAt8nHmAc45WsW2pRwQaE73ECg8TL3JUMdInTBYnnGufch6l1OvZpR
  2o9IH3w1ZczmCHa55LmUcj4b11YhASu+jhxhwS+fRA6hAtC0iQ2VFfExVYqZ8Uu7
  uPhTWngEIuRFeqdLR1/OOhdtk0mpC0gZfZ8HjViH4w4Mkm20Wd/DuIMCgYEA2xfK
  RapiszLFTP8S2LFGFRoIldfISYBaA9tT5tvszqr+Vzlg7m2f7ldwxEGcaBFjCZvs
  1YXlDBB1K6sWJ1gKpbONpMWp9RKkCAgcCNOoW4LWH+4EX0rgCvvvAxc6ee6vpwAI
  mQOCMnWPT0SsTgJKhLKGs3gIfo6wey0pKR9IdjUCgYAM62tTfZZ7UibeILcvdeUe
  W5C0w+9puCkRJgH+KS9WHVBOCFcjrvh4E8BvLi0WxeuZxrbUpFMSINmWLqDNU0Tm
  +onIqc9ZWmnpJ8C5LbJAQ59DMyYVN0yv+Qzq/CrWRRO5Ro9dKhf2L3VteC0g9OWN
  1iMSxZlv1an+lSWrd7ZrfwKBgQCCxQ9hR5LD3ODw1Sqdlin7fF91eKc+X9LajHXm
  zIvqyxsmWsQla99StnRDX9oIL6CKYrwYsmOFMOmO1/5QG3e3cZVwrN6FvcuUU6rQ
  Be1uOYiu5DVN33YceEUv9hRcJQBI0HdRRUvX7F1OdfHWWf26eIh35IRFbcueqdTw
  i5CHpQKBgGnfjipYO6eUQuZIGocODpc/Wf1/5R2CkNmRbCeCFWN87yFCAR/zg+L+
  SQee6YXnrbWj4AR8ibZKKLvq/na98PTUjmo7QPx//mSsWAsFTv3nllprZ0zqcKtF
  JC9GGJEOpkNCnzPOMKbWQVwfNdOEnTw72V2A2zisTROMUaDjFhrH
  -----END RSA PRIVATE KEY-----
LANGUAGE_CODE: vi
LMS_HOST: trainficient.com
LMS_LANGUAGE: vi
LMS_LANGUAGES:
- en
- vi
MOUNTS:
- /home/ubuntu/edx-platform
- /home/ubuntu/frontend-app-learning
- /home/ubuntu/frontend-app-learner-dashboard
- /home/ubuntu/frontend-app-discussions
- /home/ubuntu/frontend-app-authn
- /home/ubuntu/frontend-app-account
- /home/ubuntu/frontend-app-profile
- /home/ubuntu/frontend-app-course-authoring
- /home/ubuntu/frontend-app-ora
- /home/ubuntu/frontend-app-ora-grading
MYSQL_ROOT_PASSWORD: pYG3J3OE
OPENEDX_EXTRA_PIP_REQUIREMENTS:
- git+https://github.com/ZiecThanh09/xblock-in-video-quiz@master
OPENEDX_MYSQL_PASSWORD: IFlCdFJg
OPENEDX_SECRET_KEY: 9uHUit9KuDGSGQssX4ybBeFL
PLATFORM_NAME: Trainficient
PLUGINS:
- aspects
- forum
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
RALPH_ADMIN_HASHED_PASSWORD: $2b$12$3v2RT71Va2.ztuXIdzo5WeXHbkcGq5Q9Q6l2iuR08e6TWx1LHaDBu
RALPH_ADMIN_PASSWORD: npzbjpbeijcciczfzzciksbnqrxeoufkhxcq
RALPH_ADMIN_USERNAME: ralph
RALPH_LMS_HASHED_PASSWORD: $2b$12$LJbo2EnhKWYRrns7muJuBu.bdVrYs444ZkJIhJ3pFIAjykafUvU8e
RALPH_LMS_PASSWORD: uqzkrjdqzkksadnourspnhmrkcvyvqcrckqe
RALPH_LMS_USERNAME: lms
RUN_SMTP: false
SMTP_HOST: smtp.gmail.com
SMTP_PASSWORD: jsgp pcyy vohc fcit
SMTP_PORT: 587
SMTP_USERNAME: trainficient.official@gmail.com
SMTP_USE_SSL: false
SMTP_USE_TLS: true
SUPERSET_ADMIN_PASSWORD: tTm2IMYveN212bzb9EtbECAJ
SUPERSET_ADMIN_USERNAME: g1KsS0orDVqz
SUPERSET_DB_PASSWORD: mIVzfFyY0bHNQhYdtxyatUjm
SUPERSET_LMS_PASSWORD: TUjSaIeVIUf3p0NUfkzq4lWE
SUPERSET_LMS_USERNAME: WaPnnrsdywDs
SUPERSET_OAUTH2_CLIENT_ID: 6xnHAvISRMDwBHo1
SUPERSET_OAUTH2_CLIENT_ID_DEV: m3GoOcQ5dZEUls57
SUPERSET_OAUTH2_CLIENT_SECRET: AqGyGM9UlHTiVG0h
SUPERSET_ROW_LEVEL_SECURITY_XAPI_GROUP_KEY: xapi_course_id
SUPERSET_SECRET_KEY: 9pvK4zgdk638rPGeY6WHTEVI
THEME_NAME: indigo
